// AUTO-GENERATED by the pipeline (publish.deploy_site). Do not edit by hand.
import type { SiteData } from './types';
export const site: SiteData = {
  "issueNo": 1,
  "issueDate": "JUL 06 2026",
  "totalChanges": 243,
  "critCount": 1,
  "notableCount": 18,
  "fyiCount": 224,
  "subscribeUrl": "https://stacktrace-web.vercel.app/#subscribe",
  "critical": {
    "tool": "Vercel AI SDK",
    "version": "@ai-sdk/provider-utils@5.0.4",
    "summary": "This patch fixes a prototype pollution vulnerability in synchronous provider JSON parsing. The fix prevents malicious JSON inputs from polluting the prototype chain, and exposes a `secureJsonParse` utility for safer JSON handling.",
    "action": ""
  },
  "notable": [
    {
      "tool": "Vercel AI SDK",
      "version": "@ai-sdk/anthropic@4.0.8",
      "summary": "Fixed a bug where `thinking: { type: 'disabled' }` was silently dropped from API requests instead of being forwarded to Anthropic. This fix corrects behavior for models that default thinking on, preventing unexpected token budget consumption."
    },
    {
      "tool": "Resend",
      "version": "v6.17.1",
      "summary": "The resource field has been removed from the API in v6.17.1. If your application references this field, you must update your code before deploying this version."
    },
    {
      "tool": "Resend",
      "version": "v6.17.0",
      "summary": "Resend v6.17.0 adds idempotencyKey support to the emails.receiving.forward() method and introduces OAuth grant management capabilities. These are new stable features for the email API with no breaking changes."
    }
  ],
  "feed": [
    {
      "name": "v16.3.0-canary.78",
      "version": "v16.3.0-canary.78",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/workflow-harness@1.0.18",
      "version": "@ai-sdk/workflow-harness@1.0.18",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/workflow@1.0.15",
      "version": "@ai-sdk/workflow@1.0.15",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/vue@4.0.15",
      "version": "@ai-sdk/vue@4.0.15",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/tui@1.0.15",
      "version": "@ai-sdk/tui@1.0.15",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/svelte@5.0.15",
      "version": "@ai-sdk/svelte@5.0.15",
      "tier": "fyi"
    }
  ],
  "tools": [
    "Stripe",
    "Supabase",
    "Neon",
    "Turso",
    "Vercel",
    "Railway",
    "Cloudflare Workers",
    "Prisma",
    "Drizzle ORM",
    "Kysely",
    "Clerk",
    "Auth.js",
    "Better Auth",
    "Resend",
    "Trigger.dev",
    "Inngest",
    "Vercel AI SDK",
    "OpenAI SDK",
    "Anthropic SDK",
    "Next.js",
    "tRPC",
    "shadcn/ui",
    "Radix UI",
    "Tailwind CSS",
    "Bun",
    "Deno",
    "Payload CMS",
    "Directus",
    "PocketBase",
    "Liveblocks"
  ]
} as SiteData;
