// AUTO-GENERATED by the pipeline (publish.deploy_site). Do not edit by hand.
import type { SiteData } from './types';
export const site: SiteData = {
  "issueNo": 2,
  "issueDate": "JUL 13 2026",
  "totalChanges": 517,
  "critCount": 3,
  "notableCount": 34,
  "fyiCount": 480,
  "subscribeUrl": "https://stacktrace-web.vercel.app/#subscribe",
  "critical": {
    "tool": "Vercel AI SDK",
    "version": "@ai-sdk/openai-compatible@2.0.58",
    "summary": "Fixed a security vulnerability where streaming tool calls could finalize prematurely on partial JSON, causing tool execution with incomplete arguments. This affects any application using streaming tool calls with the OpenAI-compatible SDK.",
    "action": "Update @ai-sdk/openai-compatible to 2.0.58 immediately if using streaming tool calls in production."
  },
  "notable": [
    {
      "tool": "Vercel AI SDK",
      "version": "@ai-sdk/cartesia@3.0.0",
      "summary": "The Vercel AI SDK now includes a first-party Cartesia provider (v3.0.0 stable) supporting Sonic 3.5 speech generation, Ink-Whisper batch transcription, and Ink 2 realtime transcription. This is a new GA integration, not a breaking change to existing APIs."
    },
    {
      "tool": "Anthropic SDK",
      "version": "sdk-v0.111.0",
      "summary": "Anthropic TypeScript SDK v0.111.0 adds support for the new 'dreaming' API capability and gates session tool calls on evaluated permissions with idle bounded by server stop_reason. No breaking changes; both additions are additive to the stable release."
    },
    {
      "tool": "Trigger.dev",
      "version": "v4.5.3",
      "summary": "Trigger.dev v4.5.3 removes support for the end-of-life v3 `trigger dev` CLI; v3 users will get an upgrade message instead of connecting. Also includes a TypeScript declaration fix for `chat.agent` exports and server-side perf/bug fixes."
    }
  ],
  "feed": [
    {
      "name": "@ai-sdk/groq@3.0.51",
      "version": "@ai-sdk/groq@3.0.51",
      "tier": "fyi"
    },
    {
      "name": "@ai-sdk/groq@4.0.8",
      "version": "@ai-sdk/groq@4.0.8",
      "tier": "fyi"
    },
    {
      "name": "v16.3.0-canary.83",
      "version": "v16.3.0-canary.83",
      "tier": "fyi"
    },
    {
      "name": "@clerk/nextjs@7.5.17",
      "version": "@clerk/nextjs@7.5.17",
      "tier": "fyi"
    },
    {
      "name": "@clerk/fastify@3.1.50",
      "version": "@clerk/fastify@3.1.50",
      "tier": "fyi"
    },
    {
      "name": "@clerk/tanstack-react-start@1.4.17",
      "version": "@clerk/tanstack-react-start@1.4.17",
      "tier": "fyi"
    }
  ],
  "tools": [
    "Stripe",
    "Supabase",
    "Neon",
    "Turso",
    "Vercel",
    "Railway",
    "Cloudflare Workers",
    "Prisma",
    "Drizzle ORM",
    "Kysely",
    "Clerk",
    "Auth.js",
    "Better Auth",
    "Resend",
    "Trigger.dev",
    "Inngest",
    "Vercel AI SDK",
    "OpenAI SDK",
    "Anthropic SDK",
    "Next.js",
    "tRPC",
    "shadcn/ui",
    "Radix UI",
    "Tailwind CSS",
    "Bun",
    "Deno",
    "Payload CMS",
    "Directus",
    "PocketBase",
    "Liveblocks"
  ]
} as SiteData;
